services:
  # Backend Web Service
  - type: web
    name: foodify-backend
    env: node
    plan: free
    region: singapore
    rootDir: backend # Point to the backend folder
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  # Frontend Static Site
  - type: web
    name: foodify-frontend
    env: static
    plan: free
    region: singapore
    rootDir: frontend # Point to the frontend folder
    buildCommand: npm install && npm run build
    staticPublishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: foodify-backend
          property: host
    # Standard React router handling for SPAs
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
